### ISSUE TITLE
Angular 11, "CommonJS or AMD dependencies can cause optimization bailouts" warning

### ISSUE THREAD

**Issue by tyeety** [fingerpich/jalali-moment#108]
After updating project to Angular 11, serve warns that "**example.ts depends on 'jalali-moment'. CommonJS or AMD dependencies can cause optimization bailouts. For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies**"

I have no idea what this warning is, as well as I don't care what this warning is, as we see many new error and warnings after each angular update. But I will appreciate you if you fix it. (Or if you don't. By the way, we are all thankful)

**Comment by fingerpich** [comment]
Moment.js uses commonJS and doesn't work well with modern "tree shaking" algorithms, so it tends to increase the size of web application bundles and jalali-moment is a plugin for this module so we cant do it.

Thank you.

**Comment by ghost** [comment]
so. basically there is no solution?

**Comment by fingerpich** [comment]
The solution is. using other libraries as I mentioned in the readme.md
Please take a look at [day.js](https://github.com/iamkun/dayjs), [jalaliday](https://github.com/alibaba-aero/jalaliday) modules.
