### ISSUE TITLE
jalali-moment with vite and vue not working 

### ISSUE THREAD

**Issue by pooyasis** [fingerpich/jalali-moment#118]
I Create my project with vite and Vue3 with default setting as explained in https://v3.vuejs.org/guide/installation.html#vite 
but when I try to run it it shows this message 

**Uncaught TypeError: moment.localeData is not a function
    at jalali-moment.js:11708**

jalali-moment works fine when using vue cli, but with **vite**  it's not wokring

here is my package.json file
{
  "name": "Pouya_Soft",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "jalali-moment": "^3.3.10",
    "vue": "^3.0.4"
  },
  "devDependencies": {
    "vite": "^1.0.0-rc.13",
    "@vue/compiler-sfc": "^3.0.4"
  }
}

**Comment by Dev-Addict** [comment]
same problem with react and vite

**Comment by Real-Pooria** [comment]
Same problem it doesn't work with vite.

**Comment by fingerpich** [comment]
I created a demo and see the problem, I will fix it soon
https://stackblitz.com/edit/github-5xca5r-5rvyvv?file=src/main.js

Please create demo for the issues

**Comment by fingerpich** [comment]
Fixed in 3.3.11
https://stackblitz.com/edit/github-5xca5r-8wvdns?file=package.json
