### ISSUE TITLE
ایراد نمایش در بخش ثانیه

### ISSUE THREAD

**Issue by mrr-r** [fingerpich/jalali-moment#125]
با سلام و خسته نباشید برای ساخت این پلاگین،
در بخش فرمت‌بندی ثانیه به دقیقه می چسبد و بد نمایش داده می شود.
![1](https://user-images.githubusercontent.com/66952858/167670450-8756776a-8f89-4d0e-ab65-ecdddf904aaa.png)
و این بعد از کابرد پلاگین هست:
![2](https://user-images.githubusercontent.com/66952858/167670838-edcdb133-43f1-4ec1-bce9-0996149d659d.png)

خواهشمندم بررسی کنید شاید ایراد از سمت من باشد.

**Comment by fingerpich** [comment]
Hi
Its not related to this library, you can see the [test.js](https://github.com/fingerpich/jalali-moment/blob/master/test.js) file and make sure that there isn't such a problem.
