### ISSUE TITLE
timezone  in 1402 is not correct !  

### ISSUE THREAD

**Issue by Ahmedkurd** [fingerpich/jalali-moment#133]
in the 2023 timezone Iran did not change but when converting UTC time to Shamsi date not add +3:30 add +4:30 , how to solve the problem

**Comment by MR-omid** [comment]
same here!
please fix it 🙏

**Comment by montajebi** [comment]
Has problems with it, Please fix this.

**Comment by Ahmedkurd** [comment]
you should change the operating system timezone +03:30

**Comment by MR-omid** [comment]
> you should change the operating system timezone +03:30

+03:30 is not timezone, its offset.

OS timezone is correctly set to ASIA/TEHRAN.
