### ISSUE TITLE
update typings

### ISSUE THREAD

**Issue by peymanebrahimi** [fingerpich/jalali-moment#23]
Thank you for your wonderful effort.
Jalali functions such as m.jYear() can not be recognized in vscode, "jalali-moment": "^**2.0.4**", "@angular / cli": "^1.3.0", "typescript": "~2.3.3".
However your plunkr at https://embed.plnkr.co/Gggh1u/ works fine, even after updating jalali-moment to 2.0.4, and also it does not need moment itself, but I had to npm install "moment" in my angular/cli project.

But in the component after,
  `import * as pmoment from 'jalali-moment';` and
  `this.jalaliYear = ( < any > pmoment( ) ).jYear( );`
it works as expected.

**Comment by fingerpich** [comment]
Hi,
Thank you!
jalali-moment uses moment as its dependency so when you install jalali-moment it will install moment.js automatically.
I think you have used somewhere this code `import * as moment from 'moment';` and moment point to moment.js not jalali-moment.

**Comment by peymanebrahimi** [comment]
Hi,
In my angular 4 project,
There is no `import * as moment from 'moment';` for sure.
On top of the component, there is:
`import * as pmoment from 'jalali-moment'; ` and
inside of the body of a method: 
`const b = pmoment();
b.jYear(); // jYear is not available here` 
and typescript complains about it.

**Comment by fingerpich** [comment]
It works well on plunker so the problem is in your project.
please make a plunker like your project or review your code you will find the problem.

**Comment by peymanebrahimi** [comment]
ok
