### ISSUE TITLE
manipulating by day

### ISSUE THREAD

**Issue by peymanebrahimi** [fingerpich/jalali-moment#24]
Does this method works correctly on version 2.1.2?
m.add(1, "**jDay**");
or
m.add(1 "**jD**");
inside unitOfTime type base:
 jDay and jD 
are defined, but they do not work for me.

**Comment by fingerpich** [comment]
Adding days in Jalali and Gregorian system are equal
so use Gregorian system to add days as the next code `m.add(1, 'day')` 
but it will be OK as you expect.
Thank you.

**Comment by peymanebrahimi** [comment]
then I use 
m.add(1, 'day')
thanks
