### ISSUE TITLE
Any option to validate jalali date?

### ISSUE THREAD

**Issue by lvlohammadi** [fingerpich/jalali-moment#25]
Hi Mojtaba, Thank you for the service.
Is there any validation option for jalali dates in this lib? As you know, in momentjs a `isValid` function doing the similar work. So, can you point out how we can validate jalali dates using `jalali-moment` ? 
According to your knowledge, What do you do if you want check and validate month, day and year in jalali calendar?

**Comment by fingerpich** [comment]
Hi, Thank you
`isValid()` method works well on both calendar system.
`moment('1370/07/31','jYYYY/jMM/jDD').isValid(); // false`

I have just added validation to [this demo](https://plnkr.co/edit/caWsmd?p=preview)

**Comment by lvlohammadi** [comment]
Thanks. I had already tried this, but it seems to work well now.
