### ISSUE TITLE
Usage on stackblitz.com

### ISSUE THREAD

**Issue by peymanebrahimi** [fingerpich/jalali-moment#34]
Hi mate,
[My angular projects](https://github.com/peymanebrahimi/AngularMaterialJalaliDate) works fine locally either by ` ng serve ` or ` ng build --prod `.
But on [stackblitz](https://stackblitz.com/edit/angular-jalali-datepicker) it says ` ERROR TypeError: jmoment is not a function `.
Would you please look at that?

Thanks in advance as always.

**Comment by fingerpich** [comment]
Hi mate,
glad to see you
have you used the same version of jalali moment in project?

**Comment by peymanebrahimi** [comment]
yes.
github and stackblitz both have 3.0.6

**Comment by fingerpich** [comment]
Its related to stackblitz
It does not load jalali-moment if you remove jalali moment from dependencies the error remains the same. 
and also [plunker demo](https://plnkr.co/edit/caWsmd?p=info) works well too.

**Comment by peymanebrahimi** [comment]
hi,
have a look at here:
https://github.com/stackblitz/core/issues/218#issuecomment-353467782
and it worked for me too.
however in vs code, although it compiles but complains that ` jalali-moment has no default export `.

**Comment by fingerpich** [comment]
Hi mate,
have you tested [moment.js](https://momentjs.com) on stackblitz?
if it has the problem too [there](http://momentjscom.readthedocs.io/en/latest/moment/00-use-it/08-typescript/) is a solution for it

**Comment by peymanebrahimi** [comment]
Thanks 
it was useful.
