### ISSUE TITLE
Displaying meaningless dates after parsing in YYYY-MM-DD format

### ISSUE THREAD

**Issue by javidsapand** [fingerpich/jalali-moment#36]
I am using jalali-angular-datepicker in reactive, When i parse todays date in (YYYY-MM-DD) format, the date shown is like this (0775-09-21). I think it parses the date twice, how to avoid it.

**Comment by fingerpich** [comment]
Hi
could you please reproduce it in plunker?
I think you make the moment object in a wrong way you should use the following way
```
moment('miladi date')
moment('shamsi date', 'jYYYY/jMM/jDD')
```
or
```
moment.locale('fa');
moment('shamsi date');
```
[demo in plunker](https://plnkr.co/edit/caWsmd?p=preview)

**Comment by javidsapand** [comment]
Here is the  [Stackblitz demo](https://stackblitz.com/edit/angular-qdcznw)

**Comment by fingerpich** [comment]
try this
```
    this.testForm = this.formBuilder.group({
      date: [moment().format('YYYY-MM-DD')],
    });
```
as you see in [this component document ](https://github.com/fingerpich/jalali-angular-datepicker) input should be moment object or format as iso 8601 Notation.

**Comment by peymanebrahimi** [comment]
const d1: string = moment('1396-12-12', 'jYYYY-jMM-jDD').format('YYYY-MM-DD');
    const d2: string = '2018-03-03';
    this.testForm = this.formBuilder.group({
      date: [d1],
      date2: [d2]
    });

**Comment by javidsapand** [comment]
Thanks a lot both of you guys @fingerpich and @peymanebrahimi
