### ISSUE TITLE
Force to supporting jalali calender

### ISSUE THREAD

**Issue by m-farahmand** [fingerpich/jalali-moment#38]
I use this module to localizing mat-datepicker and in some cases it call functions without argument ( e.g. year() return Gregorian year ).

I want to know why year, month and ... functions return Gregorian instead of jalali  when they call without argument.<br>
**Thank you for your effort**

**Comment by fingerpich** [comment]
It's fixed in [jalali-moment@3.1.2](https://www.npmjs.com/package/jalali-moment)
