### ISSUE TITLE
Error with existing moment@2.22.1

### ISSUE THREAD

**Issue by amirriazi** [fingerpich/jalali-moment#39]
First of all thanks for you  nice work.
When I use in my node project which already dependent to moment@2.22.1 I've got this message:
//*** code 
const shamsi =jmoment('2014/01/24').locale('fa').format('YYYY/MM/DD');

//*** what it shows in console: 
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 1989/01/24, _f: undefined, _strict: undefined, _locale: [object Object]
Error ........... 

Thanks again.
Mohammad

**Comment by fingerpich** [comment]
Hi
Your welcome
2014/01/24 its not in ISO or RFC2822 formats.
you could use
``` moment('24/01/2014')```
or
``` moment('2014/01/24',  'YYYY/MM/DD');```
and I will update the document
Thank you

**Comment by amirriazi** [comment]
Thank you again it works now. I appreciate it.
