### ISSUE TITLE
[FEATURE REQUEST] Add CLI tool

### ISSUE THREAD

**Issue by NightMachinary** [fingerpich/jalali-moment#40]
Add a CLI tool to easily use these capabilities. Most useful for me personally are the two commands `GregorianToJalali` and `JalaliToGregorian`.

**Comment by fingerpich** [comment]
Hi,
great idea
and also it could be useful to replace every Gregorian dates with Jalali or vise versa in texts.
and why do you need it as a CLI?

**Comment by NightMachinary** [comment]
CLI is very easy to use and fast. Launching a separate app or a website
just to convert a date is tedious. And CLI can be used in scripts, too.
