### ISSUE TITLE
Please create new release without error

### ISSUE THREAD

**Issue by essivision** [fingerpich/jalali-moment#42]
Please put new release of library in release section. I tested release v2.0.1 but it doesn't work. finally I copy your library from `https://unpkg.com/jalali-moment@3.1.2/dist/jalali-moment.browser.js` and okay it.

**Comment by fingerpich** [comment]
Hi,
Could you explain that more "Please put new release of library in release section"?
How did you install it? do you use npm?

**Comment by essivision** [comment]
بردار این فایلی که آدرسشو دادم 
`https://unpkg.com/jalali-moment@3.1.2/dist/jalali-moment.browser.js`
درست کار می کنه و توی کنسول خطا نمیده ولی  اونیکه توی بخش ریلیز هست مشکل داره و وقتی به پروژه اضافه می کنیم خطای 
require locale/fa 
میده. اگه خودت تست کنی متوجه میشی

ممنون

**Comment by essivision** [comment]
https://github.com/fingerpich/jalali-moment/releases

**Comment by fingerpich** [comment]
I am so sorry
I haven't pushed tags since version 2.0.1
thank you, It fixed now.
