### ISSUE TITLE
Ability to change days or month name 

### ISSUE THREAD

**Issue by nimahkh** [fingerpich/jalali-moment#43]
we have something bad here , 
Friday has been translated to  " آدینه "  and it is not normal , please set an ability to change this words ( like a translate sheet )

**Comment by fingerpich** [comment]
Hi,
Please use the following code

```js
import * as moment from 'jalali-moment';
moment().localeData()._weekdays[5] = 'jomee'
moment().locale('fa').localeData()._weekdays[5] = 'جمعه'
```

**Comment by nimahkh** [comment]
thank you , it solved my problem ,
