### ISSUE TITLE
Using with bootstrap-material-calendar

### ISSUE THREAD

**Issue by hrsh** [fingerpich/jalali-moment#47]
I use `jalali-moment-browse.js` with `bootstrap-material-calendar`. It works fine, except shortday names rensers as an `I`. May you please help me?

**Comment by fingerpich** [comment]
Thank you now I see the problem, but I have used short days in [this datepicker](https://github.com/fingerpich/jalali-angular-datepicker) and its fine
I can help you to fix it if you make a demo in plunker or stackblitz.
