### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'calSystem' of undefined

### ISSUE THREAD

**Issue by rzkhosroshahi** [fingerpich/jalali-moment#55]
**Describe the bug**
After bundling [my package](https://github.com/rzkhosroshahi/react-jalali-datepicker/tree/styling) into dist file. when I used `npm link` to test package I got an error: TypeError: Cannot read property 'calSystem' of undefined. this decelered in jalali-moment  module.

**Comment by fingerpich** [comment]
Fixed in #56
