### ISSUE TITLE
Why  jalali-moment packages  remove from my project when i install typescript package?

### ISSUE THREAD

**Issue by AmirHosein20** [fingerpich/jalali-moment#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fingerpich** [comment]
Hi,
Please make a better issue and describe the bug more
Thanks

**Comment by AmirHosein20** [comment]
I install the jalali-moment and it work ,just after the npm install typescript on my project , jalali-moment packages has removed from my project

**Comment by fingerpich** [comment]
So you say if I ran the following commands
npm i jalali-moment -S
npm i typescript -D
jalali-moment would not be in node_modules?

**Comment by AmirHosein20** [comment]
> So you say if I ran the following commands
> 
> ```
> npm i jalali-moment -S
> npm i typescript -D
> ```
> jalali-moment would not be in node_modules?

yes , of course i ran this
```
 npm i jalali-moment 
 npm i typescript 
```

**Comment by fingerpich** [comment]
تا اونجا که من فهمیدم میگی که وقتی تایپ اسکریپت رو بعد از جلالی مامنت نصب میکنی جلالی مامنت حذف میشه و دیگه تو
node_modules 
نیست
درسته؟

**Comment by AmirHosein20** [comment]
بله - همین طور هست

**Comment by fingerpich** [comment]
Its not related to jalali moment
but to find the problem run the following script in terminal
```
mkdir newproject
cd newproject
npm install jalali-moment
npm install typescript
if [ -d ./node_modules/jalali-moment ]
then 
    echo "jalali-moment present"
else
    echo "jalali-moment not present"
fi
```
I ran it and it showed me jalali-moment present
