### ISSUE TITLE
The last day of Shari var, YYYY/06/31, is not valid date

### ISSUE THREAD

**Issue by rezashami** [fingerpich/jalali-moment#60]
**Describe the bug**
When I use moment with this syntax, the program say "the date is not valid":
var miladiDate=moment("1397-06-31", 'YYYY-MM-DD');
// miladiDate is invalid date
Is there any way for convert this date to gregorian date?
Thank you for your answers.

P.S: I use node.js version 10.15.1 and the latest version of jalali-moment

**Comment by fingerpich** [comment]
Hi, thanks
please provide a [stackblitz](https://stackblitz.com) demo.

**Comment by rezashami** [comment]
> Hi, thanks
> please provide a [stackblitz](https://stackblitz.com) demo.

https://stackblitz.com/edit/react-4aeamf?embed=1&file=Moment

**Comment by fingerpich** [comment]
We will continue fixing the bug in #61

**Comment by fingerpich** [comment]
please create a PR if you can fix the problem.

**Comment by pouyamiralayi** [comment]
Hi! where is the code related to this problem? i would be happy to contribute.
Thanks!

**Comment by rezafrad** [comment]
Hi!
there is a bug converting 1398-08-09.
instead of 2019-10-31 returns 2019-11-01

**Comment by fingerpich** [comment]
> > Hi, thanks
> > please provide a [stackblitz](https://stackblitz.com) demo.
> 
> https://stackblitz.com/edit/react-4aeamf?embed=1&file=Moment

you have to use jmoment.locale('fa') at first or use jmoment.from('1397-06-29', 'fa', 'YYYY-MM-DD') to read the input as a jalali time
[demo](https://stackblitz.com/edit/react-o2vhyv?file=index.js)

**Comment by fingerpich** [comment]
> Hi!
> there is a bug converting 1398-08-09.
> instead of 2019-10-31 returns 2019-11-01

I have tested it and it works well [demo](https://stackblitz.com/edit/react-pqkxqx?file=index.js)
