### ISSUE TITLE
jMoment fail when run with  moment.ISO8601 format

### ISSUE THREAD

**Issue by pouyamn** [fingerpich/jalali-moment#70]
**Describe the bug**
it raises an error when called like:
`moment.utc(value, moment.ISO_8601, true);`

**Expected behavior**
Create a jMoment object!

**Additional context**
I got rid of the error by some stupid workaround, but it should be implemented
```javascript
 function makeMoment(input, format, lang, strict, utc) {
        // if called with formats like moment.ISO8601
        if (typeof format === "function" || format === moment0.ISO_8601) format = "";
//...
```

**Comment by fingerpich** [comment]
Thanks. its fixed in 3.3.5.
