### ISSUE TITLE
not work in angular 8 prod build

### ISSUE THREAD

**Issue by Hank1370** [fingerpich/jalali-moment#71]
jalali moment not work in angular 8 prod build

**Comment by Hank1370** [comment]
تو local  درست کار میکنه ولی وقتی build میگرم تو انگولار هشت درست کار نمیگنه .

**Comment by fingerpich** [comment]
please give us a demo, at least an error

**Comment by Hank1370** [comment]
> please give us a demo, at least an error

تو
local
درست کار میکنه
ولی وقتی
build prod
میگرم تو انگولار هشت درست کار نمیگنه .
باز به صورت میلادی نشون میده .
خطای هم نمیده

**Comment by fingerpich** [comment]
so the problem is in your production process not in this library.

**Comment by irajchardoli** [comment]
@Hank1370 manam in moshkelo daram , shoma ino hal kardi?

**Comment by fingerpich** [comment]
#72
