### ISSUE TITLE
Converting to locale 'fa' not working after update

### ISSUE THREAD

**Issue by majid-n** [fingerpich/jalali-moment#72]
**Describe the bug**
Convert Gregorian date to Locale 'fa' not working after update

**To Reproduce**
1. Angular Updated from 7 to 8
2. There was an issue converting jalali date to gregorian. i have googled and saw your answer to this issue. (update to 3.3.2...)
3. updated jalali-moment to the latest version
4. now when i try to convert gregorian date to jalali it always returns gregorian

**Sample**
moment('2019/07/23').locale('fa').format('YYYY/MM/DD))
moment.from('2019/07/23', 'en', 'YYYY/MM/DD').locale('fa').format('YYYY/MM/DD))
both return **2019/07/23**

**Comment by fingerpich** [comment]
Hi
Ok i will take a look

**Comment by fingerpich** [comment]
[demo](https://stackblitz.com/edit/svelte-whkfyw) uses the last version 3.3.3 and its ok

**Comment by fingerpich** [comment]
A [demo](https://stackblitz.com/edit/angular-wmpxzl) in angular 8 that it works fine too

**Comment by majid-n** [comment]
could it be a problem with my packages ? look at this picture...

**Comment by majid-n** [comment]
so far i have discovered that the main problem is when converting from gregorian **String** to locale 'fa'.

**temporary solution :** 
instead of ->  `moment('2019/07/23').locale('fa').format('YYYY/MM/DD))`
should do ->  `moment(new Date('2019/07/23')).locale('fa').format('YYYY/MM/DD))`

**please note that moment package in the latest 2.24.0 version has many changes on locales**

**Comment by fingerpich** [comment]
Updated the [demo](https://stackblitz.com/edit/angular-wmpxzl) as you said and they works well.

**Comment by MRezaHa** [comment]
i am using angular 7, and by serving the app using "ng serve" jalali-moment  is working as expected,
but in aot compilation using "ng build --prod" its not working correctly.

**Comment by majid-n** [comment]
i have tried everything but couldn't find a solution.
my last approach is working **in some pages only** !!!
`moment(new Date('2019/07/23')).locale('fa').format('YYYY/MM/DD));`

i thought it might be an import problem that causes lack of  **'fa'** locale but it wasn't.
anyway i'm still struggling please let me now if you came up with any idea.

**Comment by MehdiSaeedifar** [comment]
We have this problem too.

**Comment by MehdiSaeedifar** [comment]
The problem refers to  #56.
I changed the jalali function code and the problem solved.

`  if (!momentObj) return false;
  return momentObj.calSystem === 1 || (moment.justUseJalali && momentObj.calSystem !== 2);`

**Comment by fingerpich** [comment]
can you please create a PR!

**Comment by fingerpich** [comment]
Have you guys tested  @MehdiSaeedifar solution? does it work for you?

**Comment by irajchardoli** [comment]
> Have you guys tested @MehdiSaeedifar solution? does it work for you?

@fingerpich for me not worked.!

**Comment by irajchardoli** [comment]
> i am using angular 7, and by serving the app using "ng serve" jalali-moment is working as expected,
> but in aot compilation using "ng build --prod" its not working correctly.

@MRezaHa I'm having the same issue , were you able to solve this issue?

**Comment by hadi-aj** [comment]
> Have you guys tested @MehdiSaeedifar solution? does it work for you?

Yes, it works. because `momentObj` is `undifined`, i think its related to Node.js version(10+).

**Comment by fingerpich** [comment]
> so far i have discovered that the main problem is when converting from gregorian **String** to locale 'fa'.
> 
> **temporary solution :**
> instead of -> `moment('2019/07/23').locale('fa').format('YYYY/MM/DD))`
> should do -> `moment(new Date('2019/07/23')).locale('fa').format('YYYY/MM/DD))`
> 
> **please note that moment package in the latest 2.24.0 version has many changes on locales**

@majid-n when i was reviewing the code i faced with a method and I remembered your problem
and I think you have used `unBindCalendarSystemAndLocale()` method in your code.

please take a look at the [demo](https://stackblitz.com/edit/svelte-meqtwr).

**Comment by fingerpich** [comment]
> The problem refers to #56.
> I changed the jalali function code and the problem solved.
> 
> ` if (!momentObj) return false; return momentObj.calSystem === 1 || (moment.justUseJalali && momentObj.calSystem !== 2);`

thank you and it has fixed.
