### ISSUE TITLE
moment locale did not change in antd-jalali-moment

### ISSUE THREAD

**Issue by hosseinmh** [fingerpich/jalali-moment#73]
hi 
i install antd-jalali-moment and add instruction for change moment locale to fa 
but moment month and year didnt change 
thanks for response

**Comment by hosseinmh** [comment]
photo is attached
![Screenshot from 2019-08-05 11-33-23](https://user-images.githubusercontent.com/12621753/62445181-e7873d00-b774-11e9-9c9e-d7acf00ee205.png)

**Comment by fingerpich** [comment]
Hi
there should be a document for it but if you want to fix your problem create a demo in stackblitz or plunker
