### ISSUE TITLE
typescript sample import is wrong

### ISSUE THREAD

**Issue by parsibox** [fingerpich/jalali-moment#74]
hi
this is true
please change it
```
import * as moment from "moment-jalaali";
```

**Comment by fingerpich** [comment]
Hi please take a look at [document](https://github.com/fingerpich/jalali-moment#typescript)
```
import * as moment from 'jalali-moment';
```

**Comment by parsibox** [comment]
this is wrong
the correct sample is :
```
import * as moment from "moment-jalaali";
```

**Comment by fingerpich** [comment]
[moment-jalaali](https://github.com/jalaali/moment-jalaali) is another library
you can see the difference in the [introduction](https://github.com/fingerpich/jalali-moment#jalali-moment)
