### ISSUE TITLE
Use Persian digits

### ISSUE THREAD

**Issue by ali4heydari** [fingerpich/jalali-moment#77]
It would be great to have an option to use Persian digits like: ۱۳۹۸/۰۷/۰۹
```js
jalaliMoment.local('fa',{usePersianDigit: true})
```
Thanks!

**Comment by fingerpich** [comment]
The main goal of this repository is to facilitate converting any library using moment.js to be compatible with jalali calendar system, if we generate persian digits we have to parse them too, and it would be hard to keep it update.
For this you can use the following package https://www.npmjs.com/package/persian-number
or use persian fonts also you can create your own fork then we will add a link to your repository.
