### ISSUE TITLE
Moment Difference returns wrong number if locale is set to 'fa'

### ISSUE THREAD

**Issue by ahmadx87** [fingerpich/jalali-moment#78]
**Describe the bug**
The package returns wrong number when you want to find the differences (day, month, year, ...) if the locale is set to 'fa'.
`moment('2019-10-26').locale('fa').diff(moment('2019-10-28').locale('fa'), 'month') // 108!!`
`moment('2019-10-26').locale('en').diff(moment('2019-10-28').locale('en'), 'month') // 0`

**To Reproduce**
see [demo](https://jsfiddle.net/ahmadx87/e6na7r39/1/)

**Comment by fingerpich** [comment]
I added a test and it worked, but why the demo is wrong? can you check the demo?

**Comment by ahmadx87** [comment]
Thank for your input.
The fiddle is pretty simple. I don't know how the tests are passing but the demo result is wrong. I even tested it again in a node environment but the result is the same. I get wrong numbers if locale is fa.

**Comment by fingerpich** [comment]
can you please check the code and find the problem?

**Comment by fingerpich** [comment]
Can you please check the 3.3.5?

**Comment by asajadian** [comment]
Sorry I didn't get a chance to get at it sooner.

**Comment by fingerpich** [comment]
good points. thank you.
can you please create a PR?

**Comment by asajadian** [comment]
Sure, I'll work on that.

**Comment by asajadian** [comment]
I created this pull request https://github.com/fingerpich/jalali-moment/pull/96
I borrowed code from the original moment diff method. The tests are passing. Hope it resolves the issue.

**Comment by fingerpich** [comment]
please check v3.3.7

**Comment by asajadian** [comment]
I did several other tests in the browser and it looks fine.
Thanks!
