### ISSUE TITLE
Cant format specific shamsi date 

### ISSUE THREAD

**Issue by Sajadkiani** [fingerpich/jalali-moment#92]
Cant format XXXX0229 date.
`  var x = moment("13900229","YYYYMMDD",'fa').format("YYYY/MM/DD");`
or 
`  var x = moment("13900229").format("YYYY/MM/DD");`

output : 
Invalid Date

**Comment by fingerpich** [comment]
Please fork the following [template](https://stackblitz.com/edit/svelte-whkfyw) to create a demo for the bug and share it here.

**Comment by Sajadkiani** [comment]
https://svelte-expf6r.stackblitz.io

**Comment by fingerpich** [comment]
if you wanted to use this kind of input `moment("13900229")` as a jalali time format for moment you would have to use `moment.locale('fa')` so it takes the input as a jalali time
[demo](https://stackblitz.com/edit/svelte-arpzst)

but I am wondering how `moment("13900228")` is working in your demo
can you please check the code and create a PR if you found the problem?

**Comment by Sajadkiani** [comment]
Okay. I try.

**Comment by Sajadkiani** [comment]
This problem is due to the fact that the date (1390-02-29) is considered the Gregorian date (according to the specified format) and this month (February 1390) is the last day of the 28th.

**Comment by fingerpich** [comment]
thanks
