### ISSUE TITLE
It determines GMT+325 for Iran's time

### ISSUE THREAD

**Issue by meness** [fingerpich/jalali-moment#93]
Please check [this out](https://codesandbox.io/s/boring-feynman-1ehgh?file=/src/index.js).

```js
const moment = require("moment");
const jalaliMoment = require("jalali-moment");

console.log(jalaliMoment.utc("09:30", "HH:mm").toDate());

console.log(moment.utc("09:30", "HH:mm").toDate());
```

**Output**
> Sat Jan 01 0000 12:55:44 **GMT+0325** (Iran Standard Time)
> Tue May 19 2020 14:00:00 **GMT+0430** (Iran Daylight Time)

**Comment by fingerpich** [comment]
Its fixed in master branch, please check.

**Comment by meness** [comment]
Thanks for the quick fix 👍 Please release a beta/stable version If tests pass then I can install through NPM
