### ISSUE TITLE
Convert Jalali To Gregorian

### ISSUE THREAD

**Issue by ghkhashayar** [fingerpich/jalali-moment#97]
Hi, I Write This Code:
`moment.from('1377/02/15', 'fa', 'YYYY/MM/DD').format('YYYY/MM/DD')
`
And Return To Me: 1377/02/15

How I Can Convert Jalali To Gregorian?

**Comment by fingerpich** [comment]
Hi, 
Please create a demo

you have used `moment.locale('fa')` so you need to use `locale('en')` before the `format` method
moment.from('1377/02/15', 'fa', 'YYYY/MM/DD').locale('en').format('YYYY/MM/DD')

**Comment by ghkhashayar** [comment]
I Try it.
not work.
it return: 1377/02/15
I use in the vue.js and install vue-jalali-moment library.

**Comment by fingerpich** [comment]
Please create a demo in stackblitz
