### ISSUE TITLE
error in angular 9 

### ISSUE THREAD

**Issue by makbari1994** [fingerpich/jalali-moment#98]
i have this error in jalali moment in angular 9 . please check it.

 line 283 . moment js.

moment.js:283 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:

**Comment by makbari1994** [comment]
line 283 . moment js.

moment.js:283 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:

**Comment by fingerpich** [comment]
Please create a demo.
